datasets:
  raw:
    housing:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/housing/housing.csv
      driver_params: {}
  
  #   product:
  #     type: ds
  #     format: csv
  #     uri: ${core.data_base_path}/raw/sales/prod_master.csv
  #     driver_params: {}
  
  # cleaned:
  #   orders:
  #     type: ds
  #     format: parquet
  #     uri: ${core.data_base_path}/cleaned/sales/orders.parquet
  #     driver_params: {}

  #   product:
  #     type: ds
  #     format: parquet
  #     uri: ${core.data_base_path}/cleaned/sales/product.parquet
  #     driver_params: {}

  #   sales:
  #     type: ds
  #     format: parquet
  #     uri: ${core.data_base_path}/cleaned/sales/sales.parquet
  #     driver_params: {}

  processed:
    housing:
      type: ds
      format: parquet
      uri:  ${core.data_base_path}/processed/housing/housing_clean.csv
      driver_params: {}

  train:
    housing:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/housing/train_features.csv
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: csv
        uri: ${core.data_base_path}/train/housing/train_target.csv
        driver_params:
          save:
            index: False
  test:
    housing:
      features:
        type: ds
        format: csv
        uri: ${core.data_base_path}/test/housing/test_features.csv
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: csv
        uri: ${core.data_base_path}/test/housing/test_target.csv
        driver_params:
          save:
            index: False
  # score:
  #   sales:
  #     output:
  #       type: ds
  #       format: parquet
  #       uri: ${core.data_base_path}/test/sales/scored_output.parquet
  #       driver_params:
  #         save:
  #           index: False